schema_version = "1.0.0"

id = "blender_log"
version = "0.0.1"
name = "Blender Log"
tagline = "Shared UI for add-ons to report, organize, and fix issues"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/tools/addons/blender_log"
tags = ["System", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2025 Demeter Dzadik & Blender Studio",
]
