schema_version = "1.0.0"

id = "blender_svn"
version = "1.0.3"
name = "Blender SVN"
tagline = "An SVN (Subversion) interface built directly into Blender"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/tools/addons/blender_svn"
tags = ["Pipeline"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2019-2025 Demeter Dzadik & Blender Studio",
]

wheels = [
  "./wheels/python_dateutil-2.8.2-py2.py3-none-any.whl",
  "./wheels/Send2Trash-1.8.0-py3-none-any.whl",
  "./wheels/six-1.16.0-py2.py3-none-any.whl",
  "./wheels/xmltodict-0.12.0-py2.py3-none-any.whl",
]

[permissions]
files = "Update/remove files in local repository"
