schema_version = "1.0.0"

id = "blender_studio_asset_pipeline"
version = "0.3.0"
name = "Blender Studio Asset Pipeline"
tagline = "Asset data merger for studio collaboration"
maintainer = "Demeter Dzadik <demeter@blender.org>"
type = "add-on"
website = "https://studio.blender.org/tools/addons/asset_pipeline"
tags = ["Pipeline"]

blender_version_min = "4.1.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2024-25 Nick Alberelli & Blender Studio"
]
[permissions]
files = "Read/Write other .blend files during asset publishing"