[tool.yapf]
BASED_ON_STYLE = "pep8"
SPACES_BEFORE_COMMENT = 4
SPLIT_BEFORE_LOGICAL_OPERATOR = true
COALESCE_BRACKETS = true
COLUMN_LIMIT = 120
CONTINUATION_ALIGN_STYLE = "VALIGN-RIGHT"
ALLOW_SPLIT_BEFORE_DEFAULT_OR_NAMED_ASSIGN = true
NO_SPACES_AROUND_SELECTED_BINARY_OPERATORS = true

[tool.black]
line-length = 120
skip-string-normalization = true
